### ISSUE TITLE
Nicer error if package is not installed?

### ISSUE THREAD

**Issue by MilesMcBain** [ropenscilabs/bindertools#13]
If a package is not installed locally the error is a bit ugly:

```
> bindertools::build_binder()
Runtime file created.
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In utils::packageDescription(package_name) :
  no package 'checkmate' was found
```

This is unlikely to happen with something you have been actively working on, but could easily happen if you just cloned or pulled changes from a collaborator.

**Comment by maelle** [comment]
This repo is being archived. For more information refer to [rOpenSci curation policy](https://devguide.ropensci.org/curationpolicy.html).

For using Binder with R we suggest trying out [holepunch](https://karthik.github.io/holepunch/)
