### ISSUE TITLE
print dockerfile

### ISSUE THREAD

**Issue by dfalster** [ropenscilabs/bindertools#15]
Nice work! 

Just wondering if it possible to also output a dockerfile, so that there is the option of running the analysis on a docker container instead of on binder?

That would give a backup in case binder doesn't continue at some point

**Comment by maelle** [comment]
This repo is being archived. For more information refer to [rOpenSci curation policy](https://devguide.ropensci.org/curationpolicy.html).

For using Binder with R we suggest trying out [holepunch](https://karthik.github.io/holepunch/)
