### ISSUE TITLE
older versions of R

### ISSUE THREAD

**Issue by smwindecker** [ropenscilabs/bindertools#16]
If this is being done retroactively for an older project does binder need to be told to use an older base r version in their docker? If so, how do we add this functionality?

**Comment by MilesMcBain** [comment]
At the moment the runtime.txt does not have any influence on the R version, the latest version is always installed. See: https://github.com/jupyter/repo2docker/issues/245

To fix, we'd have to go back to providing a dockerfile. Although from the documentation I'm reading this is not encouraged: https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html

**Comment by ajstewartlang** [comment]
I've only just started using binder, but notice that the most recent version of R that seems to be installed when I run binder is 3.4.4 - which is a bit behind where R currently is (3.5.2) - even setting today's data in the runtime.txt file in my repo doesn't result in anything more recent than 3.4.4  Am I doing something wrong?

**Comment by nuest** [comment]
Just commenting on this for other people landing here:

1. You can use a `Dockerfile` either
  - manually based on the [`rocker/binder` image](https://hub.docker.com/r/rocker/binder/tags) going back until `3.4.0`, or
  - using [`wholepunch`](https://karthik.github.io/holepunch/)
2. https://github.com/jupyter/repo2docker/pull/772/files#diff-26c1d7020998ead6f3513548c91a56b7R68 should close this for _some_ older R versions (see https://github.com/jupyter/repo2docker/pull/772/files#diff-26c1d7020998ead6f3513548c91a56b7R68) for `repo2docker` and a little while later on mybinder.org

By the way: what would you say is the relation between `bindertools` and `wholepunch` :thinking: ?

**Comment by smwindecker** [comment]
Hey! So after playing around with holepunch and chatting to Karthik, I actually think holepunch makes bindertools obsolete as they pretty much achieve the same aim to automatically populate a dockerfile and then launch the container leveraging binder instead of docker on a local machine. Not sure how to go about retiring this project, except maybe to point to the other resources in the readme?

**Comment by nuest** [comment]
Thanks for clarifying this so quickly!

A big :rotating_light: in the readme should do it IMO.

**Comment by maelle** [comment]
This repo is being archived. For more information refer to [rOpenSci curation policy](https://devguide.ropensci.org/curationpolicy.html).

For using Binder with R we suggest trying out [holepunch](https://karthik.github.io/holepunch/)
