### ISSUE TITLE
Function to create markdown code for a "launch binder" button

### ISSUE THREAD

**Issue by stevekambouris** [ropenscilabs/bindertools#2]
The function would return the markdown code for the built binder (see [binder page](https://github.com/rocker-org/binder)) with the details of the user and repo populated:
`[![Binder](http://mybinder.org/badge.svg)](http://beta.mybinder.org/v2/gh/<GITHUB_USER>/<REPO>/<BRANCH>?urlpath=rstudio)`

**Comment by maelle** [comment]
This repo is being archived. For more information refer to [rOpenSci curation policy](https://devguide.ropensci.org/curationpolicy.html).

For using Binder with R we suggest trying out [holepunch](https://karthik.github.io/holepunch/)
