### ISSUE TITLE
prevent reading over install.R

### ISSUE THREAD

**Issue by smwindecker** [ropenscilabs/bindertools#9]
make sure that the recursive reading of .R files doesn't look for the packages listed in a previously formed install.R file. @MilesMcBain we'd just need to make the 'install.R' file an exception to the R_files line in binder_installR, right?

```r
  R_files <- dir(directory, 
                 full.names = TRUE,
                 pattern = "\\.(rmd|r)$" , 
                 recursive = TRUE, 
                 ignore.case = TRUE)
```

**Comment by MilesMcBain** [comment]
Hahaha

**Comment by MilesMcBain** [comment]
Yep that should work.
